spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: admin-client
            client-secret: secret
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks